name: Agentic Bots

on:
  pull_request:
    types: [opened, synchronize, labeled]

env:
  REGISTRY: "ghcr.io/ki-reply-gmbh/silicon-shoring-agentic-bots"

jobs:
  utop-agent:
    name: UTOP Agent - Unit Test Optimization
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'agent:utop') || contains(github.event.pull_request.labels.*.name, 'improve-tests') || contains(github.event.pull_request.labels.*.name, 'mutation-testing')
    timeout-minutes: 30
    container:
      image: ghcr.io/ki-reply-gmbh/silicon-shoring-agentic-bots/utop-agent:latest
    steps:
      - name: Run UTOP Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: echo "UTOP Agent would run here"

  tech-debt-agent:
    name: Technical Debt Agent - SonarQube-based improvements
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'agent:tech-debt') || contains(github.event.pull_request.labels.*.name, 'fix-debt') || contains(github.event.pull_request.labels.*.name, 'code-quality')
    timeout-minutes: 20
    container:
      image: ghcr.io/ki-reply-gmbh/silicon-shoring-agentic-bots/tech-debt-agent:latest
    steps:
      - name: Run Tech Debt Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_PROJECT_KEY: ${{ secrets.SONARQUBE_PROJECT_KEY }}
        run: echo "Tech Debt Agent would run here"

  test-agent:
    name: Test Agent - Automated test generation
    runs-on: ubuntu-latest
    if: false  # Disabled by default - change to enable
    timeout-minutes: 25
    container:
      image: ghcr.io/ki-reply-gmbh/silicon-shoring-agentic-bots/test-agent:latest
    steps:
      - name: Run Test Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: echo "Test Agent would run here"
